language: node_js
node_js:
  - '8'
branches:
  only:
    - master
    - develop
    - '/^v.*$/'
before_script:
  - npm install
before_deploy:
  - npm run prerelease
deploy:
  - provider: npm
    skip_cleanup: true
    edge: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: C7fYJsE00wulwb3KEJfk3XeBVR+9rbToJOqbctZgnK5ns6pAu9e7sJnqKUQG1bY4iTKcHNPI3MMmse5+xjr1pBXQ6KPqcacXcJTLbGppib1/SiJftJ/lHZwVxtGREoVon+9K54uPScTNfPkXEuf+gLXluoQgwyB4WwQHwkk+ImMYVwUlvz6/Lo9ExQvQ6ULPpsI6N4Wx03WdUi+gTFpgfJiMb2fQi4for5KbxCAove7vgHqSC4ENKDWwzT3R1M9vU0eaf0z8lYa0aC80abUhWXVbcf0p6s9bLpQ+u78l+sWTUPpUqfXOQtL0tYBA5p7owY9PZID8vXTgEr0EQ8gtFsg4QSMgqnGnaq9r0CGRsN6OBpDKPG/4KKz2XAvG42/qCcvVy9QV41lfN6IPhDdKDnMi2bpfcnHGuug639FuMqOI9UROFNjrrIrvaEtrX1YVPyU5EqawA/O16skyNocYx0Ho/9x47b+JIhseBdq2W5Y1lASDJiPXcBc6MAqWcwGz/veSTFcSxN3a70nC7qnIC12gr0nj0UOnvGyvPm2RjYYa4KOlvU8QNmeJ+88k01JngQQpPYAilr1zJH+rM9A0Ix4I1dAePJ4r3P/IEs0xuJVV1xfElqf3/WakLddvinPA9pQFgKXVYaKOJshm6AoUDznQfxJmHkjD3YILMW8q0E8=
    on:
      tags: true
      repo: higlass/higlass-pileup
      branch: master
  - provider: releases
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: BVbTrhDPh3t7FAhYN97v3sH6aP5qj8oG2+0cxWxXZhTf2/Ih508YPEBLGcvx4/LhjkUZCy/X3Ewqg0G0AZAJSZYgSruuUtLIFeTSs0VkV/Kcxvrn4ejlPQQ+cLaxi1xcmZPwRUvJNyH2ZdliwJ7ZVrB9kkbr86Qfmvkj2BbjobyCtu6peq2GgzqSHVEkqnBZx3Ycb23tqvRwuz2satj0UkAfOcugq0rnGhGCurOa9DJ1718Gt8AzFNiNj2D4r3dTFlqX93LRf8/B0H3S3sABwZFqil1bW1/R0gv4r7wppX6+mDAgHQwwQm4Xvp2BPinhE9OTePIA6t+2VxsyGPqOb+zrs/eQpLZwdvbFYylFjEBsrnN5o8vZ2m4rrf6hQMnQJ6+vO77n8Zpe4z0zMh+FVWo7p7Ozg9jin8FOMkUyIL1Ga+TUldqkzKNJMiDINp+EmsIJrIjC0BQwnDpy4KPRsIEgZCf8SMrLmy8yHbOoHQwh5RerfVFD1SOGIM5ORcDVNBz4UtwiDHp0zjmefHap8Aq5A7O7T2nFnE9Vd2sMbYBC7ciMtCYwt1bfkfwzUk7HbhAytWAIftX6zdspn6JES23Z2opjaNJi7Ol8wMud9WiELQ1/Agsu4JDLdQrFAowG1TZ53rXytH0HJ9Uknpa/8tLXNWOul/Pv77bgeDXelZk=
    file: dist.zip
    on:
      tags: true
      repo: higlass/higlass-pileup
      branch: master
